# Generated by Django 2.1.5 on 2022-09-15 03:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_write', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
            ],
            options={
                'db_table': 'reviews_comments',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_write', models.DateTimeField(auto_now_add=True)),
                ('time_retouch', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_shared', models.IntegerField()),
                ('book', models.ForeignKey(db_column='isbn13', on_delete=django.db.models.deletion.DO_NOTHING, to='books.Book')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
