# Generated by Django 2.1 on 2022-08-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_write', models.DateTimeField()),
                ('time_retouch', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('rate', models.IntegerField()),
                ('is_shared', models.IntegerField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
