# Generated by Django 2.1 on 2022-09-02 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_write', models.DateTimeField()),
                ('time_retouch', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('rate', models.IntegerField()),
                ('is_shared', models.IntegerField()),
                ('isbn13', models.ForeignKey(db_column='isbn13', on_delete=django.db.models.deletion.DO_NOTHING, to='books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmmelier_reviews',
            },
        ),
    ]
