# Generated by Django 4.0.6 on 2022-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
