# Generated by Django 2.1 on 2022-09-02 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn13', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('vol', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=1200, null=True)),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('publisher', models.CharField(blank=True, max_length=1000, null=True)),
                ('pub_date', models.CharField(blank=True, max_length=10, null=True)),
                ('img_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('kdc_class_no', models.CharField(blank=True, max_length=20, null=True)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmmelier_books',
            },
        ),
    ]
