# Generated by Django 4.0.6 on 2022-08-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Bookmmelier_book',
        ),
    ]
