# Generated by Django 2.1.5 on 2022-09-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220913_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='like_users',
        ),
    ]
