# Generated by Django 2.1.5 on 2022-09-15 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('debate_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.TextField()),
            ],
            options={
                'db_table': 'debates',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('debate', models.ForeignKey(db_column='debate_id', on_delete=django.db.models.deletion.CASCADE, to='debates.Debate')),
            ],
            options={
                'db_table': 'debates_message',
            },
        ),
    ]
