# Generated by Django 2.1.5 on 2022-09-13 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_remove_book_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('debate_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.Book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmmelier_debate',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('contents', models.TextField()),
                ('debate', models.ForeignKey(db_column='debate_id', on_delete=django.db.models.deletion.CASCADE, to='debates.Debate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmmelier_debate_message',
            },
        ),
    ]
