# Generated by Django 4.1.1 on 2022-09-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('debates', '0002_auto_20220915_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='book',
            field=models.ForeignKey(db_column='isbn13', on_delete=django.db.models.deletion.DO_NOTHING, related_name='debates', to='books.book'),
        ),
    ]
