# Generated by Django 4.1.1 on 2022-09-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0003_alter_debate_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='owner',
            new_name='user',
        ),
    ]
